apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 3000 # Port the service will expose
      targetPort: 3000 # Port your app listens on in the container
      nodePort: 30007 # Port on the node (host) to forward to (30000–32767 range)
